package scalan.plugin

import scalan.meta.ScalanAst.SEntityModuleDef

/** The object contains the current state and temporary data of the plugin. */
object ScalanPluginState {
  import scala.collection.mutable.Map
  /** Mapping of module name to its extensions that should be generated by the plugin.
    * For example: Segments -> Set(SegmentsDsl, SegmentsDslSeq, SegmentsDslExp) */
  val extMap = Map[String, Set[String]](
    "WPredefs" -> Set("WPredefsDsl", "WPredefsDslSeq", "WPredefsDslExp"),
    "WGenIterables" -> Set("WGenIterablesDsl", "WGenIterablesDslSeq", "WGenIterablesDslExp"),
    "WCanBuildFroms" -> Set("WCanBuildFromsDsl", "WCanBuildFromsDslSeq", "WCanBuildFromsDslExp"),
    "WArrays" -> Set("WArraysDsl", "WArraysDslSeq", "WArraysDslExp"),
    "WArrayOpss" -> Set("WArrayOpssDsl", "WArrayOpssDslSeq", "WArrayOpssDslExp"),
    "WWrappedArrays" -> Set("WWrappedArraysDsl", "WWrappedArraysDslSeq", "WWrappedArraysDslExp"),
    "WNums" -> Set("WNumsDsl", "WNumsDslSeq", "WNumsDslExp"),
    "WDoubleNums" -> Set("WDoubleNumsDsl", "WDoubleNumsDslSeq", "WDoubleNumsDslExp"),
    "WNumMonoids" -> Set("WNumMonoidsDsl", "WNumMonoidsDslSeq", "WNumMonoidsDslExp"),
    "WPlusMonoids" -> Set("WPlusMonoidsDsl", "WPlusMonoidsDslSeq", "WPlusMonoidsDslExp"),
    "WCols" -> Set("WColsDsl", "WColsDslSeq", "WColsDslExp"),
    "WVecs" -> Set("WVecsDsl", "WVecsDslSeq", "WVecsDslExp"),
    "WDenseVecs" -> Set("WDenseVecsDsl", "WDenseVecsDslSeq", "WDenseVecsDslExp"),
    "WMatrs" -> Set("WMatrsDsl", "WMatrsDslSeq", "WMatrsDslExp"),
    "WDenseMatrs" -> Set("WDenseMatrsDsl", "WDenseMatrsDslSeq", "WDenseMatrsDslExp"),
    "WMatrOps" -> Set("WMatrOpsDsl", "WMatrOpsDslSeq", "WMatrOpsDslExp"),
    "WBaseMatrOps" -> Set("WBaseMatrOpsDsl", "WBaseMatrOpsDslSeq", "WBaseMatrOpsDslExp")
  )

  ScalanPluginConfig.codegenConfig.entityFiles.foreach { file =>
    val fileNameParts = file.split('.')
    if (!fileNameParts.isEmpty) {
      val moduleName = fileNameParts.head
      extMap(moduleName) = Set(moduleName + "Dsl", moduleName + "DslSeq", moduleName + "DslExp")
    }
  }

  /** Mapping between modules and another modules used by them. */
  val usageMap = Map[String, List[String]](
    "Nums" -> List("LinearAlgebra"),
    "NumMonoids" -> List("Nums","LinearAlgebra"),
    "Cols" -> List("NumMonoids","LinearAlgebra"),
    "Vecs" -> List("NumMonoids", "Cols", "LinearAlgebra"),
    "Matrs" -> List("NumMonoids", "Cols", "Vecs", "LinearAlgebra"),
    "MatrOps" -> List("Nums", "NumMonoids", "Vecs", "Matrs", "LinearAlgebra"),
    "LinearAlgebra" -> List("NumMonoids", "Cols", "Vecs", "Matrs"),
    "LinearAlgebraOps" -> List("LinearAlgebra")
  )

  /** Mapping of module name to the package where it is defined. */
  val pkgOfModule = Map[String, String](
    "Nums" -> "scalanizer",
    "NumMonoids" -> "scalanizer",
    "Cols" -> "scalanizer.collections",
    "Vecs" -> "scalanizer.linalgebra",
    "Matrs" -> "scalanizer.linalgebra",
    "MatrOps" -> "scalanizer.linalgebra",
    "LinearAlgebra" -> "scalanizer.linalgebra",
    "LinearAlgebraOps" -> "scalanizer.linalgebra"
  )

  case class WrapperDescr(module: SEntityModuleDef, ownerChain: List[String])
  /** Mapping of external type names to their wrappers. */
  val wrappers = Map[String, WrapperDescr]()
  /** Names of external types. They must be read only after the WrapFrontend phase. */
  def externalTypes = wrappers.keySet
}
